apiVersion: v1
kind: Service
metadata:
  namespace: my-spark
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: my-spark
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysql
          image: mysql:5.7.41
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_DATABASE
              value: my_db
            - name: MYSQL_ROOT_PASSWORD
              value: my_root
            - name: MYSQL_USER
              value: my
            - name: MYSQL_PASSWORD
              value: my
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              cpu: 0.5
              memory: 1Gi
          ports:
            - containerPort: 3306
              name: mysql
