version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092"
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_EXTERNAL://${MY_DOCKER_HOST:-localhost}:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT

  topics:
    image: confluentinc/cp-kafka:7.1.1
    depends_on:
      - kafka
    command: |
      bash -c 'cub kafka-ready -b kafka:9092 1 50 && \
        kafka-topics --create --topic raw \
          --partitions 2 --replication-factor 1 --bootstrap-server kafka:9092'
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
