version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.1.1
    depends_on:
      - zookeeper
    ports:
      - "9092"
      - "19092:19092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_EXTERNAL://${MY_DOCKER_HOST:-localhost}:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT

  topics:
    image: confluentinc/cp-kafka:7.1.1
    depends_on:
      - kafka
    command: |
      bash -c 'cub kafka-ready -b kafka:9092 1 50 && \
        kafka-topics --create --topic raw \
          --partitions 2 --replication-factor 1 --bootstrap-server kafka:9092 && \
        kafka-topics --create --topic raw2 \
          --partitions 2 --replication-factor 1 --bootstrap-server kafka:9092'
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored

  flink-jm:
    build:
      context: .
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm
        env.log.dir: /tmp/flink-logs
        restart-strategy: fixed-delay
        restart-strategy.fixed-delay.attempts: 15
        restart-strategy.fixed-delay.delay: 10 s
    volumes:
      - ./savepoints:/mnt/savepoints
      - ./target:/mnt/artifacts:ro
    command:
      - jobmanager

  flink-tm1:
    build:
      context: .
    depends_on:
      - flink-jm
    ports:
      - "5006:5006"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jm
        taskmanager.numberOfTaskSlots: 4
        env.log.dir: /tmp/flink-logs
    volumes:
      - ./savepoints:/mnt/savepoints
      - ./output:/mnt/output
    command:
      - taskmanager
