/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.psolomin.records;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class ConsumedEvent extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -4993941571494235805L;

    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser()
            .parse(
                    "{\"type\":\"record\",\"name\":\"ConsumedEvent\",\"namespace\":\"com.psolomin.records\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"shard_id\",\"type\":\"string\"}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<ConsumedEvent> ENCODER =
            new BinaryMessageEncoder<ConsumedEvent>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<ConsumedEvent> DECODER =
            new BinaryMessageDecoder<ConsumedEvent>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<ConsumedEvent> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<ConsumedEvent> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<ConsumedEvent> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<ConsumedEvent>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this ConsumedEvent to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a ConsumedEvent from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a ConsumedEvent instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static ConsumedEvent fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private long id;
    private java.lang.CharSequence shard_id;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public ConsumedEvent() {}

    /**
     * All-args constructor.
     * @param id The new value for id
     * @param shard_id The new value for shard_id
     */
    public ConsumedEvent(java.lang.Long id, java.lang.CharSequence shard_id) {
        this.id = id;
        this.shard_id = shard_id;
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return id;
            case 1:
                return shard_id;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                id = (java.lang.Long) value$;
                break;
            case 1:
                shard_id = (java.lang.CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'id' field.
     * @return The value of the 'id' field.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the 'id' field.
     * @param value the value to set.
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the 'shard_id' field.
     * @return The value of the 'shard_id' field.
     */
    public java.lang.CharSequence getShardId() {
        return shard_id;
    }

    /**
     * Sets the value of the 'shard_id' field.
     * @param value the value to set.
     */
    public void setShardId(java.lang.CharSequence value) {
        this.shard_id = value;
    }

    /**
     * Creates a new ConsumedEvent RecordBuilder.
     * @return A new ConsumedEvent RecordBuilder
     */
    public static com.psolomin.records.ConsumedEvent.Builder newBuilder() {
        return new com.psolomin.records.ConsumedEvent.Builder();
    }

    /**
     * Creates a new ConsumedEvent RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new ConsumedEvent RecordBuilder
     */
    public static com.psolomin.records.ConsumedEvent.Builder newBuilder(
            com.psolomin.records.ConsumedEvent.Builder other) {
        if (other == null) {
            return new com.psolomin.records.ConsumedEvent.Builder();
        } else {
            return new com.psolomin.records.ConsumedEvent.Builder(other);
        }
    }

    /**
     * Creates a new ConsumedEvent RecordBuilder by copying an existing ConsumedEvent instance.
     * @param other The existing instance to copy.
     * @return A new ConsumedEvent RecordBuilder
     */
    public static com.psolomin.records.ConsumedEvent.Builder newBuilder(com.psolomin.records.ConsumedEvent other) {
        if (other == null) {
            return new com.psolomin.records.ConsumedEvent.Builder();
        } else {
            return new com.psolomin.records.ConsumedEvent.Builder(other);
        }
    }

    /**
     * RecordBuilder for ConsumedEvent instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConsumedEvent>
            implements org.apache.avro.data.RecordBuilder<ConsumedEvent> {

        private long id;
        private java.lang.CharSequence shard_id;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.psolomin.records.ConsumedEvent.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.shard_id)) {
                this.shard_id = data().deepCopy(fields()[1].schema(), other.shard_id);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing ConsumedEvent instance
         * @param other The existing instance to copy.
         */
        private Builder(com.psolomin.records.ConsumedEvent other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.shard_id)) {
                this.shard_id = data().deepCopy(fields()[1].schema(), other.shard_id);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'id' field.
         * @return The value.
         */
        public long getId() {
            return id;
        }

        /**
         * Sets the value of the 'id' field.
         * @param value The value of 'id'.
         * @return This builder.
         */
        public com.psolomin.records.ConsumedEvent.Builder setId(long value) {
            validate(fields()[0], value);
            this.id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'id' field has been set.
         * @return True if the 'id' field has been set, false otherwise.
         */
        public boolean hasId() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'id' field.
         * @return This builder.
         */
        public com.psolomin.records.ConsumedEvent.Builder clearId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'shard_id' field.
         * @return The value.
         */
        public java.lang.CharSequence getShardId() {
            return shard_id;
        }

        /**
         * Sets the value of the 'shard_id' field.
         * @param value The value of 'shard_id'.
         * @return This builder.
         */
        public com.psolomin.records.ConsumedEvent.Builder setShardId(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.shard_id = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'shard_id' field has been set.
         * @return True if the 'shard_id' field has been set, false otherwise.
         */
        public boolean hasShardId() {
            return fieldSetFlags()[1];
        }

        /**
         * Clears the value of the 'shard_id' field.
         * @return This builder.
         */
        public com.psolomin.records.ConsumedEvent.Builder clearShardId() {
            shard_id = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public ConsumedEvent build() {
            try {
                ConsumedEvent record = new ConsumedEvent();
                record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
                record.shard_id =
                        fieldSetFlags()[1] ? this.shard_id : (java.lang.CharSequence) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<ConsumedEvent> WRITER$ =
            (org.apache.avro.io.DatumWriter<ConsumedEvent>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<ConsumedEvent> READER$ =
            (org.apache.avro.io.DatumReader<ConsumedEvent>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
        out.writeLong(this.id);

        out.writeString(this.shard_id);
    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.id = in.readLong();

            this.shard_id = in.readString(this.shard_id instanceof Utf8 ? (Utf8) this.shard_id : null);

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.id = in.readLong();
                        break;

                    case 1:
                        this.shard_id = in.readString(this.shard_id instanceof Utf8 ? (Utf8) this.shard_id : null);
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}
